import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1a1a1a]`}
      >
        <nav className="bg-[#0D0D0D] h-[200px] w-[100%] flex justify-center items-center">
          <div className="flex w-[226px] h-[40px] gap-2">
            <Image
              aria-hidden
              src="/rocket.png"
              alt="Globe icon"
              width={25}
              height={36}
            />

            <Image
              aria-hidden
              src="/todo_App.png"
              alt="Globe icon"
              width={192}
              height={48}
            />
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
